server:
  port: 8080
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 139.159.227.224
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enabled: true
  redis-manager:
    host: 139.159.227.224:6379
zhang:
  jwt:
    # secret
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # 有效时长
    expire: 604800
    header: Authorization