server:
  port: 8080
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javazy?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
  redis:
    host: 139.159.227.224
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enabled: true
  redis-manager:
    host: 139.159.227.224:6379
rsa:
  encrypt:
    debug: false # true表示开启调试，不加密。（方便开发时测试）
    # 更换为自己的公钥
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBeKFwUbfHTYEP95lxPSUqtsbW24vH2rCFG4f1SgXXUPE7gJp9XnlfGfl6BEME+t0ecUTtGgGn97KNXvCPA9AaSMTId5WnNjYi8mDWq4zojflZOTI5q8ikpV9OR3DLZwPkuCHDqOjEWbV/2CI3W55IzGrl5GNZe289IqfsJ0Rg8QIDAQAB
    # 更换为自己的秘钥
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMF4oXBRt8dNgQ/3mXE9JSq2xtbbi8fasIUbh/VKBddQ8TuAmn1eeV8Z+XoEQwT63R5xRO0aAaf3so1e8I8D0BpIxMh3lac2NiLyYNarjOiN+Vk5MjmryKSlX05HcMtnA+S4IcOo6MRZtX/YIjdbnkjMauXkY1l7bz0ip+wnRGDxAgMBAAECgYBD4WEzGVjTspu/0G2jz4JE1FA7flgyzMX2TcyMAWa/PwUEjYCm0Ajhlyly6B/jlWkTj0ZRsjg2iK+67j6Uzw+qLKcqnK9DWBAf7ou/KXtru3CudrFyyHEzhbgJt0TYvt8ancLbtfPjzfZa83lT7ye6oItwiry3BqUkJKzMRK8oiQJBAO59ftV//m5sDdsLB/Byafcej45D1gfvriNX6krhw7s+vB9ObxkAOxJkUZPJNGnp/v5zTqzFHFme6lMfL1JwSAcCQQDPrPzb+rdfYwhCEYqJYCGSX9rA0gFKEYVLPEe85FsQFU1Tzf4ApiPENYmhCnBhJxkD5XQZyf7WSIhRzlUvjKFHAkEA5zR0tKh8UjKhEBzWmo1hG3jeNU6gfVsoWA1QDz5l0e5U1IjmfbdSjVcCGyLxlEiMs8O3nxkMjfnZM7JE30gJGwJBALJ1h9CNERjB5C3KHw9P8Wl0P2nkzMDWb4GoakkSvoICnDGA2V27Zw7LptohO1LxIxjrCyrCHuAK8kHCGgfDRC8CQE6ijxmFAgWCwgekEL4swxXiTIiKbuFDUKZqtfMfLqVO2amOjVLc5HyIU30fvymPoJAvu+ZSsSpQGLJ7mPp2MOc=
